config/routes.rb
Rails.application.routes.draw do
  # authenticate :user do
  #   resources   resources :conversations do
  #     resources :messages
  #   end
  # end

  resources :conversations, only: [:new, :create, :show, :display_elements, :messages_as_json] do
    get 'messages_as_json' => 'conversations#messages_as_json', as: :messages_as_json
    post 'display_elements' => 'conversations#display_elements', as: :display_elements
    post 'clear_history' => 'conversations#clear_history', as: :clear_history
    resources :messages, only: [:create, :show]
  end

  root 'conversations#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/friendlyable.rb
module Friendlyable
  extend ActiveSupport::Concern

  included do
    extend ::FriendlyId
    before_create :set_hash_id
    friendly_id :hash_id
  end

  def set_hash_id
    hash_id = nil
    loop do
      hash_id = SecureRandom.urlsafe_base64(9).gsub(/-|_/,('a'..'z').to_a[rand(26)])
      break unless self.class.name.constantize.where(:hash_id => hash_id).exists?
    end
    self.hash_id = hash_id
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  include Friendlyable
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def new
  end

  def create
    @conversation = Conversation.new({user1: '???', user2: params[:username]})
    @conversation.save

    redirect_to @conversation
  end

  def show
    @conversation = Conversation.friendly.find(params[:id])
  end

  def index
    @conversations = Conversation.all
  end

  def display_elements
    @conversation = Conversation.friendly.find(params[:conversation_id])
    if @conversation[:display_html?]
      @conversation[:display_html?] = false
    else
      @conversation[:display_html?] = true
    end
    @conversation.save
    redirect_to @conversation
  end

  def clear_history
    @conversation = Conversation.friendly.find(params[:conversation_id])
    @conversation.messages.delete_all
    redirect_to @conversation
  end

  def messages_as_json
    @conversation = Conversation.friendly.find(params[:conversation_id])
    output_hash = {}
    output_hash['display_html?'] = @conversation[:display_html?]
    messages_array = []
    @conversation.messages.each do |message|
      message_hash = {}
      message_hash['to'] = message.to
      message_hash['from'] = message.from
      message_hash['content'] = message.content
      message_hash['created_at'] = message.created_at
      messages_array.push message_hash
    end
    output_hash['messages'] = messages_array
    render :json => output_hash
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  http_basic_authenticate_with name: "BigBillyMoneyBags", password: "21b341bf77e44006eeaecf446d4646c546d399792951b989a572ee6dc3240333",
                                 only: [:show]

  def create
    @conversation = Conversation.friendly.find(params[:conversation_id])
    @message = @conversation.messages.create(message_params)

    # writes flat file for selenium script to read later
    if @message[:user_generated]
      f = File.new("cache/messages/c_#{@conversation[:hash_id]}_m_#{@message[:id]}.txt", "w")
      f.write "/conversations/#{@conversation[:hash_id]}/messages/#{@message[:id]}"
      f.close
    end

    redirect_to @conversation
  end

  def show
    @conversation = Conversation.friendly.find(params[:conversation_id])
    @message = Message.find(params[:id])
  end

  private
  def message_params
    params.require(:message).permit(:to, :from, :content, :user_generated)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/index.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<h1>Conversations</h1>

<div id="convo-count"><strong>Current Conversation Count: <%=@conversations.count %></strong></div>

<% @conversations.each do |convo| %>
  <%= link_to(conversation_path(convo)) %>
<% end %>

app/views/conversations/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<div class="container">
  <h1>MysteryRandoChat.io</h1>
  <h2>Start a new conversation</h2>

  <%= form_with scope: :conversation, url: conversations_path, local: true do |form|  %>
    <p>
      <%= form.label :username %><br>
      <%= form.text_field :username %><br>
    </p>
    <p>
      <%= form.submit 'Start Chatting'%>
    </p>
  <% end %>
</div>

app/views/conversations/show.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>

<script>
  var last_updated = Date.now();
  function escapeHtml(text) {
      return text
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;")
          .replace(/"/g, "&quot;")
          .replace(/'/g, "&#039;");
  }
  function load_initial_messages(){
      $.ajax({
          url: `<%= conversation_messages_as_json_path(@conversation[:hash_id]) %>`,
          type: "get",
          cache: false
      }).done(function( ret ) {
          ret['messages'].forEach(function(message){
                if(message['from'] == '???'){
                    $("#message-history").append(`<strong style="color:blue">From ${message["from"]} to Me</strong><br>`);
                } else {
                    $("#message-history").append(`<strong style="color:red">From Me to ${message["to"]}</strong><br>`);
                }
                if(ret['display_html?'] == true){
                    $("#message-history").append(message['content']).append("<br>");
                } else {
                    $("#message-history").append(escapeHtml(message['content'])).append("<br>");
                }
          });
      });
  }
  function get_new_messages(){
      $.ajax({
          url: `<%= conversation_messages_as_json_path(@conversation[:hash_id]) %>`,
          type: "get",
          cache: false
      }).done(function( ret ) {
          ret['messages'].forEach(function(message){
              if(Date.parse(message['created_at']) > last_updated){
                  if(message['from'] == '???'){
                      $("#message-history").append(`<strong style="color:blue">From ${message["from"]} to Me</strong><br>`);
                  } else {
                      $("#message-history").append(`<strong style="color:red">From Me to ${message["to"]}</strong><br>`);
                  }
                  if(ret['display_html?'] == true){
                      $("#message-history").append(message['content']).append("<br>");
                  } else {
                      $("#message-history").append(escapeHtml(message['content'])).append("<br>");
                  }
              }
          });
          last_updated = Date.now();
      });
  }
  load_initial_messages();
  setInterval("get_new_messages()", 5000);
  </script>

<div class="container">
  <h1>MysteryRandoChat.io</h1>
  <h2>Conversation with <%= @conversation.user1 %></h2>

  <div class="row">
    <div class="col-lg" id="message-history"></div>
    <div class="col-2">
      <div class="row">
        <%= button_to "Clear Message History", conversation_clear_history_path(@conversation) %>
      </div>
      <div class="row">
        <%= button_to "Enable/Disable Embedded Images", conversation_display_elements_path(@conversation) %>
      </div>
    </div>
  </div>

  <div class="row" style="padding-top: 20px">
    <h3>Send New Message</h3>
  </div>
  <div class="row">
    <%= form_with(model: [ @conversation, @conversation.messages.build ], local: true) do |form| %>
      <p>
        <%= form.hidden_field :to, value: @conversation[:user1] %>
        <%= form.hidden_field :from, value: @conversation[:user2] %>
        <%= form.hidden_field :user_generated, value: true %>
        <%= form.text_area :content , value: params[:content], rows: 10, cols: 100, class: "col-lg-auto",style: "min-width: 100%" %><br>
        <%= form.submit "Send"%>
      </p>
    <% end %>
  </div>
  <div class="row">
    <p style="color:red;"><strong>Note: </strong>Due to the extremely secure design of this service, it may take up to a minute for messages to be delivered.</p>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/show.html.erb
<h1>Conversation <%= @conversation.id.to_s %> Message <%= @message.id.to_s %></h1>
<p>
  <strong>From <%= @message.from %></strong>
</p>
<p>
  <strong>Message Body:</strong>
</p>
<p>
  <%= raw @message.content %>
</p>
<h3>Respond back</h3>
<%= form_with(model: [ @conversation, @conversation.messages.build ], local: true) do |form| %>
  <p>
    <%= form.hidden_field :to, value: @conversation[:user2] %>
    <%= form.hidden_field :from, value: @conversation[:user1] %>
    <%= form.text_area :content %><br>
    <%= form.submit %>
  </p>
<% end %>